-- Drop table if it already exists
DROP TABLE IF EXISTS PRODUCTS;

-- Create PRODUCTS table
CREATE TABLE PRODUCTS (
  PRODUCTID INT PRIMARY KEY IDENTITY(1,1),
  PRODUCTNAME NVARCHAR(100) NOT NULL,
  PRICE DECIMAL(10, 2) NOT NULL,
  STOCK INT NOT NULL
);

-- Insert sample data
INSERT INTO PRODUCTS (PRODUCTNAME, PRICE, STOCK) VALUES
('Laptop', 999.99, 10),
('Mouse', 25.50, 100),
('Monitor', 299.99, 5);
